#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'commonChild' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING s1
#  2. STRING s2
#

def commonChild(s1, s2):
    # Write your code here

    # Create a 2D array 'arr' initialized with 0s. The dimensions of the array are based on the lengths of 's1' and 's2' increased by 1.
    arr = [[0 for _ in range(len(s1)+1)] for _ in range(len(s2)+1) ]

    # Loop through the rows of the 2D array starting from 1 (skipping the first row).
    for i in range(1,len(s1)+1,1):

        # Loop through the columns of the 2D array starting from 1 (skipping the first column).
        for j in range(1,len(s2)+1,1):

            # Calculate the value for the current cell by taking the maximum of three possibilities:
            # 1. If the characters at s1[i-1] and s2[j-1] are the same, add 1 to the value in the diagonal cell (top-left) and assign it.
            # 2. The value in the cell above.
            # 3. The value in the cell to the left.
            arr[i][j]=max(
                ((arr[i-1][j-1] +1) if s1[i-1]==s2[j-1] else arr[i-1][j-1]),
                arr[i-1][j],
                arr[i][j-1]
            )

    # Return the value in the bottom-right cell of the 2D array, which represents the longest common subsequence.
    return arr[-1][-1]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s1 = input()

    s2 = input()

    result = commonChild(s1, s2)

    fptr.write(str(result) + '\n')

    fptr.close()
