#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort2' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort2(n, arr):
    # Write your code here
    for i in range(1, len(arr)):
        for k in range(i):
            temp = arr[i]
            if arr[k] > arr[i]:
                arr[i] = arr[k]
                arr[k] = temp
            else:
                continue
        for num in arr:
                print(num, end = " ")
        print(end = "\n")

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)
