#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    length = len(arr)
    temp = arr[length - 1]

    for i in range(length, 0, -1):
        if temp < arr[i - 2]:
            if arr[i - 2] == arr[-1]:
                arr[i - 1] = temp
                for num in arr:
                    print(num, end = " ")
                print(end = "\n")
            else:
                arr[i - 1] = arr[i - 2]
                for num in arr:
                    print(num, end = " ")
                print(end = "\n")

        else:
            arr[i - 1] = temp
            for num in arr:
                print(num, end = " ")
            break

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
