#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superReducedString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def superReducedString(s):
    # Write your code here
    st=[]
    for i in s:
        if not st:
            st.append(i)
        else:
            if st[-1]==i:
                st.pop()
            else:
                st.append(i)
    if not st:
        return 'Empty String'
    else:
        return ''.join(st)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = superReducedString(s)

    fptr.write(result + '\n')

    fptr.close()
